---
- name: Pull teeproxy image
  docker_image:
    name: "{{ teeproxy_image }}"
    tag: "{{ teeproxy_version }}"

- name: Create a teeproxy container
  docker_container:
    name: "teeproxy"
    image: "{{ teeproxy_image }}:{{ teeproxy_version }}"
    command: "teeproxy -l :{{ teeproxy_port }} -a {{ backend_a }} -b {{ backend_b }}"
    entrypoint: "teeproxy -l :{{ teeproxy_port }} -a {{ backend_a }} -b {{ backend_b }}"
    state: started
    recreate: yes
    restart_policy: always
    ports:
      - "{{ teeproxy_port }}:{{ teeproxy_port }}"
